In [ ]:
# MOUNT GOOGLE DRIVE
from google.colab import drive
drive.mount('/content/drive')
# IMPORT LIBRARIES
import os
import pandas as pd
import numpy as np
# CHECK DRIVE
print("="*80)
print("GOOGLE DRIVE CONTENT")
print("="*80)
print(os.listdir("/content/drive/MyDrive"))
# DATASET PATH
dataset_path = "/content/drive/MyDrive/Dataset/final_dataset.csv"
# CHECK FILE EXISTS
if os.path.exists(dataset_path):
    print("\n Dataset Found")
else:
    raise FileNotFoundError(f"\n Dataset Not Found\n\n{dataset_path}")
# LOAD DATASET
df = pd.read_csv(dataset_path)
print("\nDataset Loaded Successfully")
# DATASET OVERVIEW
print("="*80)
print("DATASET OVERVIEW")
print("="*80)
print(f"Shape : {df.shape}")
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")
# DATASET INFO
print("="*80)
print("DATASET INFO")
print("="*80)
df.info()
# COLUMN NAMES
print("="*80)
print("COLUMN NAMES")
print("="*80)
for i,col in enumerate(df.columns,1):
    print(f"{i}. {col}")
# DATA TYPES
print("="*80)
print("DATA TYPES")
print("="*80)
print(df.dtypes)
# MISSING VALUES
print("="*80)
print("MISSING VALUES")
print("="*80)
missing = pd.DataFrame({
    "Missing Values":df.isnull().sum(),
    "Percentage":round((df.isnull().sum()/len(df))*100,2)
})
display(missing)
# DUPLICATES
print("="*80)
print("DUPLICATES")
print("="*80)
duplicates = df.duplicated().sum()
print("Duplicate Rows :",duplicates)
# STATISTICS
print("="*80)
print("STATISTICAL SUMMARY")
print("="*80)
display(df.describe())
# FIRST 5 ROWS
print("="*80)
print("FIRST 5 ROWS")
print("="*80)
display(df.head())
# LAST 5 ROWS
print("="*80)
print("LAST 5 ROWS")
print("="*80)
display(df.tail())
# UNIQUE VALUES
print("="*80)
print("UNIQUE VALUES")
print("="*80)
for col in df.columns:
    print(f"{col} : {df[col].nunique()}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
GOOGLE DRIVE CONTENT
================================================================================
['Ready Videos', 'Wheel on the bus', 'reels', 'Pending reels', 'Colab Notebooks', 'Dataset']

 Dataset Found

Dataset Loaded Successfully
================================================================================
DATASET OVERVIEW
================================================================================
Shape : (1621209, 14)
Rows : 1621209
Columns : 14
================================================================================
DATASET INFO
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621209 entries, 0 to 1621208
Data columns (total 14 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   user               1621209 non-null  object
 1   hour_window        1621209 non-null  object
 2   login_events       1621209 non-null  float64
 3   device_events      1621209 non-null  float64
 4   file_events        1621209 non-null  float64
 5   email_events       1621209 non-null  float64
 6   total_email_size   1621209 non-null  float64
 7   total_attachments  1621209 non-null  float64
 8   https_events       1621209 non-null  float64
 9   O                  1621209 non-null  int64
 10  C                  1621209 non-null  int64
 11  E                  1621209 non-null  int64
 12  A                  1621209 non-null  int64
 13  N                  1621209 non-null  int64
dtypes: float64(7), int64(5), object(2)
memory usage: 173.2+ MB
================================================================================
COLUMN NAMES
================================================================================
1. user
2. hour_window
3. login_events
4. device_events
5. file_events
6. email_events
7. total_email_size
8. total_attachments
9. https_events
10. O
11. C
12. E
13. A
14. N
================================================================================
DATA TYPES
================================================================================
user                  object
hour_window           object
login_events         float64
device_events        float64
file_events          float64
email_events         float64
total_email_size     float64
total_attachments    float64
https_events         float64
O                      int64
C                      int64
E                      int64
A                      int64
N                      int64
dtype: object
================================================================================
MISSING VALUES
================================================================================

                   Missing Values  Percentage
user                            0         0.0
hour_window                     0         0.0
login_events                    0         0.0
device_events                   0         0.0
file_events                     0         0.0
email_events                    0         0.0
total_email_size                0         0.0
total_attachments               0         0.0
https_events                    0         0.0
O                               0         0.0
C                               0         0.0
E                               0         0.0
A                               0         0.0
N                               0         0.0

================================================================================
DUPLICATES
================================================================================
Duplicate Rows : 0
================================================================================
STATISTICAL SUMMARY
================================================================================

,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,C,E,A,N
count,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06,1.621209e+06
mean,5.272972e-01,2.500480e-01,2.748449e-01,1.622233e+00,4.865454e+04,6.547268e-01,3.173989e-02,3.323553e+01,3.074644e+01,2.905259e+01,2.900055e+01,2.970145e+01
std,5.711220e-01,8.162685e-01,1.381680e+00,2.590726e+00,7.874600e+04,1.838356e+00,7.330987e-01,1.064279e+01,1.131454e+01,1.093399e+01,1.119681e+01,4.976964e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.400000e+01
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01,2.000000e+01,1.900000e+01,1.900000e+01,2.600000e+01
50%,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.966300e+04,0.000000e+00,0.000000e+00,3.600000e+01,3.400000e+01,2.800000e+01,2.700000e+01,3.000000e+01
75%,1.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,6.301900e+04,0.000000e+00,0.000000e+00,4.200000e+01,4.000000e+01,3.900000e+01,3.900000e+01,3.300000e+01
max,8.000000e+00,2.000000e+01,3.300000e+01,3.600000e+01,1.181951e+06,4.500000e+01,1.010000e+02,5.000000e+01,5.000000e+01,5.000000e+01,5.000000e+01,4.900000e+01

================================================================================
FIRST 5 ROWS
================================================================================

,user,hour_window,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,C,E,A,N
0,AAE0190,2010-01-04 08:00:00,1.0,0.0,0.0,13.0,404826.0,4.0,9.0,36,30,14,50,29
1,AAE0190,2010-01-04 09:00:00,0.0,0.0,0.0,1.0,36502.0,0.0,20.0,36,30,14,50,29
2,AAE0190,2010-01-04 10:00:00,0.0,0.0,0.0,0.0,0.0,0.0,15.0,36,30,14,50,29
3,AAE0190,2010-01-04 11:00:00,0.0,0.0,0.0,0.0,0.0,0.0,18.0,36,30,14,50,29
4,AAE0190,2010-01-04 12:00:00,0.0,0.0,0.0,0.0,0.0,0.0,9.0,36,30,14,50,29

================================================================================
LAST 5 ROWS
================================================================================

,user,hour_window,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,C,E,A,N
1621204,ZSL0305,2011-05-13 09:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,21,26,18,41,32
1621205,ZSL0305,2011-05-13 17:00:00,1.0,0.0,0.0,1.0,26769.0,0.0,0.0,21,26,18,41,32
1621206,ZSL0305,2011-05-16 09:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,21,26,18,41,32
1621207,ZSL0305,2011-05-16 11:00:00,0.0,0.0,0.0,1.0,25610.0,0.0,0.0,21,26,18,41,32
1621208,ZSL0305,2011-05-16 17:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,21,26,18,41,32

================================================================================
UNIQUE VALUES
================================================================================
user : 1000
hour_window : 11160
login_events : 9
device_events : 21
file_events : 29
email_events : 37
total_email_size : 244021
total_attachments : 37
https_events : 67
O : 41
C : 41
E : 41
A : 41
N : 30

In [ ]:
# DATE-TIME FEATURE ENGINEERING
# Convert to datetime
df["hour_window"] = pd.to_datetime(df["hour_window"])
# Extract Date-Time Features
df["year"] = df["hour_window"].dt.year
df["month"] = df["hour_window"].dt.month
df["day"] = df["hour_window"].dt.day
df["hour"] = df["hour_window"].dt.hour
df["minute"] = df["hour_window"].dt.minute
# Monday = 0 .... Sunday = 6
df["weekday"] = df["hour_window"].dt.dayofweek
# Weekend Feature
df["is_weekend"] = df["weekday"].isin([5, 6]).astype(int)
# Working Hours (08:00 AM - 06:00 PM)
df["working_hours"] = (
    (df["hour"] >= 8) &
    (df["hour"] <= 18)
).astype(int)# CHECK NEW FEATURES
print("="*80)
print("NEW FEATURES CREATED")
print("="*80)
new_features = [
    "hour_window",
    "year",
    "month",
    "day",
    "hour",
    "minute",
    "weekday",
    "is_weekend",
    "working_hours"
]
display(df[new_features].head(10))
print("\nCurrent Shape :", df.shape)

================================================================================
NEW FEATURES CREATED
================================================================================

,hour_window,year,month,day,hour,minute,weekday,is_weekend,working_hours
0,2010-01-04 08:00:00,2010,1,4,8,0,0,0,1
1,2010-01-04 09:00:00,2010,1,4,9,0,0,0,1
2,2010-01-04 10:00:00,2010,1,4,10,0,0,0,1
3,2010-01-04 11:00:00,2010,1,4,11,0,0,0,1
4,2010-01-04 12:00:00,2010,1,4,12,0,0,0,1
5,2010-01-04 18:00:00,2010,1,4,18,0,0,0,1
6,2010-01-05 08:00:00,2010,1,5,8,0,1,0,1
7,2010-01-05 09:00:00,2010,1,5,9,0,1,0,1
8,2010-01-05 10:00:00,2010,1,5,10,0,1,0,1
9,2010-01-05 18:00:00,2010,1,5,18,0,1,0,1

Current Shape : (1621209, 22)

In [ ]:
# REMOVE NON-INFORMATIVE FEATURES
df.drop(columns=["year", "minute"], inplace=True)
print("="*80)
print("UPDATED DATASET")
print("="*80)
print("Shape :", df.shape)
print("\nColumns:")
print(df.columns.tolist())

================================================================================
UPDATED DATASET
================================================================================
Shape : (1621209, 20)

Columns:
['user', 'hour_window', 'login_events', 'device_events', 'file_events', 'email_events', 'total_email_size', 'total_attachments', 'https_events', 'O', 'C', 'E', 'A', 'N', 'month', 'day', 'hour', 'weekday', 'is_weekend', 'working_hours']

In [ ]:
# RULE-BASED SECURITY SCORE ENGINE
import numpy as np
# Initial Security Score
df["security_score"] = 100.0
# RULE 1 : Outside Working Hours
df.loc[df["working_hours"] == 0, "security_score"] -= 15
# RULE 2 : Weekend Activity
df.loc[df["is_weekend"] == 1, "security_score"] -= 10
# RULE 3 : Login Behaviour
df.loc[df["login_events"] >= 2, "security_score"] -= 5
df.loc[df["login_events"] >= 4, "security_score"] -= 10
df.loc[df["login_events"] >= 6, "security_score"] -= 20
# RULE 4 : Device (USB) Activity
df.loc[df["device_events"] >= 1, "security_score"] -= 10
df.loc[df["device_events"] >= 3, "security_score"] -= 15
df.loc[df["device_events"] >= 6, "security_score"] -= 25
# RULE 5 : File Activity
df.loc[df["file_events"] >= 3, "security_score"] -= 10
df.loc[df["file_events"] >= 8, "security_score"] -= 15
df.loc[df["file_events"] >= 15, "security_score"] -= 25
# RULE 6 : Email Activity
df.loc[df["email_events"] >= 5, "security_score"] -= 5
df.loc[df["email_events"] >= 10, "security_score"] -= 10
df.loc[df["email_events"] >= 20, "security_score"] -= 20
# RULE 7 : Attachments
df.loc[df["total_attachments"] >= 1, "security_score"] -= 5
df.loc[df["total_attachments"] >= 3, "security_score"] -= 10
df.loc[df["total_attachments"] >= 6, "security_score"] -= 20
# RULE 8 : Email Size
df.loc[df["total_email_size"] > 100000, "security_score"] -= 5
df.loc[df["total_email_size"] > 1000000, "security_score"] -= 10
df.loc[df["total_email_size"] > 10000000, "security_score"] -= 20
# RULE 9 : HTTPS Activity
df.loc[df["https_events"] >= 10, "security_score"] -= 5
df.loc[df["https_events"] >= 25, "security_score"] -= 10
df.loc[df["https_events"] >= 50, "security_score"] -= 20
# RULE 10 : Psychometric Adjustment
# High Conscientiousness increases security
df.loc[df["C"] >= 40, "security_score"] += 5
# Low Conscientiousness decreases security
df.loc[df["C"] <= 20, "security_score"] -= 5
# High Neuroticism decreases security
df.loc[df["N"] >= 40, "security_score"] -= 5
# Low Agreeableness decreases security
df.loc[df["A"] <= 20, "security_score"] -= 5
# COMPOUND RULES
# USB + File Activity
mask = (df["device_events"] >= 3) & (df["file_events"] >= 10)
df.loc[mask, "security_score"] -= 20
# Email + Attachments
mask = (df["email_events"] >= 15) & (df["total_attachments"] >= 3)
df.loc[mask, "security_score"] -= 15
# Weekend + Login
mask = (df["is_weekend"] == 1) & (df["login_events"] >= 2)
df.loc[mask, "security_score"] -= 15
# Outside Working Hours + HTTPS
mask = (df["working_hours"] == 0) & (df["https_events"] >= 20)
df.loc[mask, "security_score"] -= 15
# Outside Working Hours + File
mask = (df["working_hours"] == 0) & (df["file_events"] >= 5)
df.loc[mask, "security_score"] -= 20
# USB + Outside Working Hours
mask = (df["working_hours"] == 0) & (df["device_events"] >= 2)
df.loc[mask, "security_score"] -= 25
# Heavy Email + Large Email Size
mask = (df["email_events"] >= 20) & (df["total_email_size"] >= 1000000)
df.loc[mask, "security_score"] -= 20
# Clip Score
df["security_score"] = df["security_score"].clip(0,100)
# Security Status
conditions = [
    df["security_score"] >= 85,
    (df["security_score"] >= 65) &
    (df["security_score"] < 85),
    (df["security_score"] >= 40) &
    (df["security_score"] < 65),
    df["security_score"] < 40
]
choices = [
    "Secure",
    "Suspicious",
    "Unsecure",
    "Breached"
]
df["security_status"] = np.select(
    conditions,
    choices,
    default="Secure"
)
# Labels
label_map = {
    "Secure":0,
    "Suspicious":1,
    "Unsecure":2,
    "Breached":3

}
df["label"] = df["security_status"].map(label_map)
# Results
print("="*80)
print("SECURITY STATUS DISTRIBUTION")
print("="*80)
status = df["security_status"].value_counts().reset_index()
status.columns = ["Security Status","Records"]
status["Percentage"] = (status["Records"]/len(df)*100).round(2)
display(status)
print("\nSecurity Score Summary\n")
display(df["security_score"].describe())
display(df[[
    "security_score",
    "security_status",
    "label"
]].head(20))

================================================================================
SECURITY STATUS DISTRIBUTION
================================================================================

  Security Status  Records  Percentage
0          Secure  1253539       77.32
1      Suspicious   281135       17.34
2        Unsecure    70157        4.33
3        Breached    16378        1.01

Security Score Summary

count    1.621209e+06
mean     8.876631e+01
std      1.360586e+01
min      0.000000e+00
25%      8.500000e+01
50%      9.500000e+01
75%      1.000000e+02
max      1.000000e+02
Name: security_score, dtype: float64

    security_score security_status  label
0             65.0      Suspicious      1
1             95.0          Secure      0
2             95.0          Secure      0
3             95.0          Secure      0
4            100.0          Secure      0
5            100.0          Secure      0
6            100.0          Secure      0
7             90.0          Secure      0
8             85.0          Secure      0
9            100.0          Secure      0
10           100.0          Secure      0
11           100.0          Secure      0
12            85.0          Secure      0
13            95.0          Secure      0
14            55.0        Unsecure      2
15           100.0          Secure      0
16           100.0          Secure      0
17            85.0          Secure      0
18            45.0        Unsecure      2
19           100.0          Secure      0

In [ ]:
file_p90 = df["file_events"].quantile(0.90)
file_p95 = df["file_events"].quantile(0.95)
email_p90 = df["email_events"].quantile(0.90)
https_p95 = df["https_events"].quantile(0.95)

In [ ]:
df.loc[df["file_events"] > file_p90, "security_score"] -= 10
df.loc[df["file_events"] > file_p95, "security_score"] -= 20

In [ ]:
# FINAL DATASET VALIDATION
print("="*80)
print("FINAL DATASET INFORMATION")
print("="*80)
print(f"Shape              : {df.shape}")
print(f"Rows               : {df.shape[0]}")
print(f"Columns            : {df.shape[1]}")
print("\n" + "="*80)
print("MISSING VALUES")
print("="*80)
display(pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": ((df.isnull().sum()/len(df))*100).round(2)
}))
print("\n" + "="*80)
print("DUPLICATE RECORDS")
print("="*80)
print("Duplicate Rows :", df.duplicated().sum())
print("\n" + "="*80)
print("DATA TYPES")
print("="*80)
print(df.dtypes)
print("\n" + "="*80)
print("SECURITY STATUS DISTRIBUTION")
print("="*80)
status = df["security_status"].value_counts().reset_index()
status.columns = ["Security Status","Records"]
status["Percentage (%)"] = (
    status["Records"] / len(df) * 100
).round(2)
display(status)
print("\n" + "="*80)
print("LABEL DISTRIBUTION")
print("="*80)
label_dist = df["label"].value_counts().sort_index().reset_index()
label_dist.columns = ["Label","Records"]
label_dist["Percentage (%)"] = (
    label_dist["Records"] / len(df) * 100
).round(2)
display(label_dist)
print("\n" + "="*80)
print("SECURITY SCORE SUMMARY")
print("="*80)
display(df["security_score"].describe())
print("\n" + "="*80)
print("FIRST 5 RECORDS")
print("="*80)
display(df.head())
print("\n" + "="*80)
print("LAST 5 RECORDS")
print("="*80)
display(df.tail())

================================================================================
FINAL DATASET INFORMATION
================================================================================
Shape              : (1621209, 23)
Rows               : 1621209
Columns            : 23

================================================================================
MISSING VALUES
================================================================================

                   Missing Values  Percentage (%)
user                            0             0.0
hour_window                     0             0.0
login_events                    0             0.0
device_events                   0             0.0
file_events                     0             0.0
email_events                    0             0.0
total_email_size                0             0.0
total_attachments               0             0.0
https_events                    0             0.0
O                               0             0.0
C                               0             0.0
E                               0             0.0
A                               0             0.0
N                               0             0.0
month                           0             0.0
day                             0             0.0
hour                            0             0.0
weekday                         0             0.0
is_weekend                      0             0.0
working_hours                   0             0.0
security_score                  0             0.0
security_status                 0             0.0
label                           0             0.0

================================================================================
DUPLICATE RECORDS
================================================================================
Duplicate Rows : 0

================================================================================
DATA TYPES
================================================================================
user                         object
hour_window          datetime64[ns]
login_events                float64
device_events               float64
file_events                 float64
email_events                float64
total_email_size            float64
total_attachments           float64
https_events                float64
O                             int64
C                             int64
E                             int64
A                             int64
N                             int64
month                         int32
day                           int32
hour                          int32
weekday                       int32
is_weekend                    int64
working_hours                 int64
security_score              float64
security_status              object
label                         int64
dtype: object

================================================================================
SECURITY STATUS DISTRIBUTION
================================================================================

  Security Status  Records  Percentage (%)
0          Secure  1253539           77.32
1      Suspicious   281135           17.34
2        Unsecure    70157            4.33
3        Breached    16378            1.01

================================================================================
LABEL DISTRIBUTION
================================================================================

   Label  Records  Percentage (%)
0      0  1253539           77.32
1      1   281135           17.34
2      2    70157            4.33
3      3    16378            1.01

================================================================================
SECURITY SCORE SUMMARY
================================================================================

count    1.621209e+06
mean     8.724574e+01
std      1.690339e+01
min     -3.000000e+01
25%      8.500000e+01
50%      9.500000e+01
75%      1.000000e+02
max      1.000000e+02
Name: security_score, dtype: float64

================================================================================
FIRST 5 RECORDS
================================================================================

,user,hour_window,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,...,N,month,day,hour,weekday,is_weekend,working_hours,security_score,security_status,label
0,AAE0190,2010-01-04 08:00:00,1.0,0.0,0.0,13.0,404826.0,4.0,9.0,36,...,29,1,4,8,0,0,1,65.0,Suspicious,1
1,AAE0190,2010-01-04 09:00:00,0.0,0.0,0.0,1.0,36502.0,0.0,20.0,36,...,29,1,4,9,0,0,1,95.0,Secure,0
2,AAE0190,2010-01-04 10:00:00,0.0,0.0,0.0,0.0,0.0,0.0,15.0,36,...,29,1,4,10,0,0,1,95.0,Secure,0
3,AAE0190,2010-01-04 11:00:00,0.0,0.0,0.0,0.0,0.0,0.0,18.0,36,...,29,1,4,11,0,0,1,95.0,Secure,0
4,AAE0190,2010-01-04 12:00:00,0.0,0.0,0.0,0.0,0.0,0.0,9.0,36,...,29,1,4,12,0,0,1,100.0,Secure,0

================================================================================
LAST 5 RECORDS
================================================================================

,user,hour_window,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,...,N,month,day,hour,weekday,is_weekend,working_hours,security_score,security_status,label
1621204,ZSL0305,2011-05-13 09:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,21,...,32,5,13,9,4,0,1,100.0,Secure,0
1621205,ZSL0305,2011-05-13 17:00:00,1.0,0.0,0.0,1.0,26769.0,0.0,0.0,21,...,32,5,13,17,4,0,1,100.0,Secure,0
1621206,ZSL0305,2011-05-16 09:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,21,...,32,5,16,9,0,0,1,100.0,Secure,0
1621207,ZSL0305,2011-05-16 11:00:00,0.0,0.0,0.0,1.0,25610.0,0.0,0.0,21,...,32,5,16,11,0,0,1,100.0,Secure,0
1621208,ZSL0305,2011-05-16 17:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,21,...,32,5,16,17,0,0,1,100.0,Secure,0

In [ ]:
df["security_score"] = df["security_score"].clip(0, 100)

In [ ]:
print(df["security_score"].describe())

count    1.621209e+06
mean     8.731278e+01
std      1.650529e+01
min      0.000000e+00
25%      8.500000e+01
50%      9.500000e+01
75%      1.000000e+02
max      1.000000e+02
Name: security_score, dtype: float64

In [ ]:
# FEATURE SCALING
from sklearn.preprocessing import MinMaxScaler
# Features to Scale
scale_columns = [
    "login_events",
    "device_events",
    "file_events",
    "email_events",
    "total_email_size",
    "total_attachments",
    "https_events",
    "O",
    "C",
    "E",
    "A",
    "N",
    "month",
    "day",
    "hour",
    "weekday",
    "is_weekend",
    "working_hours",
    "security_score"
]
# Initialize Scaler
scaler = MinMaxScaler()
# Scale Features
df[scale_columns] = scaler.fit_transform(df[scale_columns])
print("="*80)
print("FEATURE SCALING COMPLETED")
print("="*80)
print("\nScaled Features")
print(scale_columns)

================================================================================
FEATURE SCALING COMPLETED
================================================================================

Scaled Features
['login_events', 'device_events', 'file_events', 'email_events', 'total_email_size', 'total_attachments', 'https_events', 'O', 'C', 'E', 'A', 'N', 'month', 'day', 'hour', 'weekday', 'is_weekend', 'working_hours', 'security_score']

In [ ]:
# VALIDATE SCALING
print("="*80)
print("MIN VALUES")
print("="*80)
display(df[scale_columns].min())
print("="*80)
print("MAX VALUES")
print("="*80)
display(df[scale_columns].max())
print("="*80)
print("FIRST 10 ROWS")
print("="*80)
display(df[scale_columns].head(10))

================================================================================
MIN VALUES
================================================================================

login_events         0.0
device_events        0.0
file_events          0.0
email_events         0.0
total_email_size     0.0
total_attachments    0.0
https_events         0.0
O                    0.0
C                    0.0
E                    0.0
A                    0.0
N                    0.0
month                0.0
day                  0.0
hour                 0.0
weekday              0.0
is_weekend           0.0
working_hours        0.0
security_score       0.0
dtype: float64

================================================================================
MAX VALUES
================================================================================

login_events         1.0
device_events        1.0
file_events          1.0
email_events         1.0
total_email_size     1.0
total_attachments    1.0
https_events         1.0
O                    1.0
C                    1.0
E                    1.0
A                    1.0
N                    1.0
month                1.0
day                  1.0
hour                 1.0
weekday              1.0
is_weekend           1.0
working_hours        1.0
security_score       1.0
dtype: float64

================================================================================
FIRST 10 ROWS
================================================================================

,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,C,E,A,N,month,day,hour,weekday,is_weekend,working_hours,security_score
0,0.125,0.0,0.0,0.361111,0.342507,0.088889,0.089109,0.65,0.5,0.1,1.0,0.428571,0.0,0.100000,0.347826,0.000000,0.0,1.0,0.65
1,0.000,0.0,0.0,0.027778,0.030883,0.000000,0.198020,0.65,0.5,0.1,1.0,0.428571,0.0,0.100000,0.391304,0.000000,0.0,1.0,0.95
2,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.148515,0.65,0.5,0.1,1.0,0.428571,0.0,0.100000,0.434783,0.000000,0.0,1.0,0.95
3,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.178218,0.65,0.5,0.1,1.0,0.428571,0.0,0.100000,0.478261,0.000000,0.0,1.0,0.95
4,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.089109,0.65,0.5,0.1,1.0,0.428571,0.0,0.100000,0.521739,0.000000,0.0,1.0,1.00
5,0.125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.65,0.5,0.1,1.0,0.428571,0.0,0.100000,0.782609,0.000000,0.0,1.0,1.00
6,0.125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.65,0.5,0.1,1.0,0.428571,0.0,0.133333,0.347826,0.166667,0.0,1.0,1.00
7,0.000,0.0,0.0,0.166667,0.127161,0.000000,0.000000,0.65,0.5,0.1,1.0,0.428571,0.0,0.133333,0.391304,0.166667,0.0,1.0,0.90
8,0.000,0.0,0.0,0.194444,0.173657,0.044444,0.000000,0.65,0.5,0.1,1.0,0.428571,0.0,0.133333,0.434783,0.166667,0.0,1.0,0.85
9,0.125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.65,0.5,0.1,1.0,0.428571,0.0,0.133333,0.782609,0.166667,0.0,1.0,1.00

In [ ]:
# FINAL PREPROCESSING SUMMARY
print("="*90)
print("FINAL PREPROCESSED DATASET SUMMARY")
print("="*90)
print(f"Dataset Shape        : {df.shape}")
print(f"Total Rows           : {df.shape[0]:,}")
print(f"Total Columns        : {df.shape[1]}")
print("\n" + "="*90)
print("COLUMN NAMES")
print("="*90)
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")
print("\n" + "="*90)
print("MISSING VALUES")
print("="*90)
display(pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Percentage": ((df.isnull().sum()/len(df))*100).round(2)
}))
print("\n" + "="*90)
print("DUPLICATE ROWS")
print("="*90)
print(df.duplicated().sum())
print("\n" + "="*90)
print("DATA TYPES")
print("="*90)
print(df.dtypes)
print("\n" + "="*90)
print("SECURITY STATUS DISTRIBUTION")
print("="*90)
status = df["security_status"].value_counts().reset_index()
status.columns = ["Status","Records"]
status["Percentage"] = (
    status["Records"]/len(df)*100
).round(2)
display(status)
print("\n" + "="*90)
print("SECURITY SCORE SUMMARY")
print("="*90)
display(df["security_score"].describe())
print("\n" + "="*90)
print("FIRST 10 ROWS")
print("="*90)
display(df.head(10))
print("\n" + "="*90)
print("LAST 10 ROWS")
print("="*90)
display(df.tail(10))

==========================================================================================
FINAL PREPROCESSED DATASET SUMMARY
==========================================================================================
Dataset Shape        : (1621209, 23)
Total Rows           : 1,621,209
Total Columns        : 23

==========================================================================================
COLUMN NAMES
==========================================================================================
1. user
2. hour_window
3. login_events
4. device_events
5. file_events
6. email_events
7. total_email_size
8. total_attachments
9. https_events
10. O
11. C
12. E
13. A
14. N
15. month
16. day
17. hour
18. weekday
19. is_weekend
20. working_hours
21. security_score
22. security_status
23. label

==========================================================================================
MISSING VALUES
==========================================================================================

                   Missing  Percentage
user                     0         0.0
hour_window              0         0.0
login_events             0         0.0
device_events            0         0.0
file_events              0         0.0
email_events             0         0.0
total_email_size         0         0.0
total_attachments        0         0.0
https_events             0         0.0
O                        0         0.0
C                        0         0.0
E                        0         0.0
A                        0         0.0
N                        0         0.0
month                    0         0.0
day                      0         0.0
hour                     0         0.0
weekday                  0         0.0
is_weekend               0         0.0
working_hours            0         0.0
security_score           0         0.0
security_status          0         0.0
label                    0         0.0

==========================================================================================
DUPLICATE ROWS
==========================================================================================
0

==========================================================================================
DATA TYPES
==========================================================================================
user                         object
hour_window          datetime64[ns]
login_events                float64
device_events               float64
file_events                 float64
email_events                float64
total_email_size            float64
total_attachments           float64
https_events                float64
O                           float64
C                           float64
E                           float64
A                           float64
N                           float64
month                       float64
day                         float64
hour                        float64
weekday                     float64
is_weekend                  float64
working_hours               float64
security_score              float64
security_status              object
label                         int64
dtype: object

==========================================================================================
SECURITY STATUS DISTRIBUTION
==========================================================================================

       Status  Records  Percentage
0      Secure  1253539       77.32
1  Suspicious   281135       17.34
2    Unsecure    70157        4.33
3    Breached    16378        1.01

==========================================================================================
SECURITY SCORE SUMMARY
==========================================================================================

count    1.621209e+06
mean     8.731278e-01
std      1.650529e-01
min      0.000000e+00
25%      8.500000e-01
50%      9.500000e-01
75%      1.000000e+00
max      1.000000e+00
Name: security_score, dtype: float64

==========================================================================================
FIRST 10 ROWS
==========================================================================================

,user,hour_window,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,...,N,month,day,hour,weekday,is_weekend,working_hours,security_score,security_status,label
0,AAE0190,2010-01-04 08:00:00,0.125,0.0,0.0,0.361111,0.342507,0.088889,0.089109,0.65,...,0.428571,0.0,0.100000,0.347826,0.000000,0.0,1.0,0.65,Suspicious,1
1,AAE0190,2010-01-04 09:00:00,0.000,0.0,0.0,0.027778,0.030883,0.000000,0.198020,0.65,...,0.428571,0.0,0.100000,0.391304,0.000000,0.0,1.0,0.95,Secure,0
2,AAE0190,2010-01-04 10:00:00,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.148515,0.65,...,0.428571,0.0,0.100000,0.434783,0.000000,0.0,1.0,0.95,Secure,0
3,AAE0190,2010-01-04 11:00:00,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.178218,0.65,...,0.428571,0.0,0.100000,0.478261,0.000000,0.0,1.0,0.95,Secure,0
4,AAE0190,2010-01-04 12:00:00,0.000,0.0,0.0,0.000000,0.000000,0.000000,0.089109,0.65,...,0.428571,0.0,0.100000,0.521739,0.000000,0.0,1.0,1.00,Secure,0
5,AAE0190,2010-01-04 18:00:00,0.125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.65,...,0.428571,0.0,0.100000,0.782609,0.000000,0.0,1.0,1.00,Secure,0
6,AAE0190,2010-01-05 08:00:00,0.125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.65,...,0.428571,0.0,0.133333,0.347826,0.166667,0.0,1.0,1.00,Secure,0
7,AAE0190,2010-01-05 09:00:00,0.000,0.0,0.0,0.166667,0.127161,0.000000,0.000000,0.65,...,0.428571,0.0,0.133333,0.391304,0.166667,0.0,1.0,0.90,Secure,0
8,AAE0190,2010-01-05 10:00:00,0.000,0.0,0.0,0.194444,0.173657,0.044444,0.000000,0.65,...,0.428571,0.0,0.133333,0.434783,0.166667,0.0,1.0,0.85,Secure,0
9,AAE0190,2010-01-05 18:00:00,0.125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.65,...,0.428571,0.0,0.133333,0.782609,0.166667,0.0,1.0,1.00,Secure,0

==========================================================================================
LAST 10 ROWS
==========================================================================================

,user,hour_window,login_events,device_events,file_events,email_events,total_email_size,total_attachments,https_events,O,...,N,month,day,hour,weekday,is_weekend,working_hours,security_score,security_status,label
1621199,ZSL0305,2011-05-11 11:00:00,0.000,0.0,0.0,0.027778,0.039655,0.0,0.0,0.275,...,0.514286,0.363636,0.333333,0.478261,0.333333,0.0,1.0,1.0,Secure,0
1621200,ZSL0305,2011-05-11 17:00:00,0.125,0.0,0.0,0.000000,0.000000,0.0,0.0,0.275,...,0.514286,0.363636,0.333333,0.739130,0.333333,0.0,1.0,1.0,Secure,0
1621201,ZSL0305,2011-05-12 08:00:00,0.125,0.0,0.0,0.000000,0.000000,0.0,0.0,0.275,...,0.514286,0.363636,0.366667,0.347826,0.500000,0.0,1.0,1.0,Secure,0
1621202,ZSL0305,2011-05-12 12:00:00,0.000,0.0,0.0,0.027778,0.024503,0.0,0.0,0.275,...,0.514286,0.363636,0.366667,0.521739,0.500000,0.0,1.0,1.0,Secure,0
1621203,ZSL0305,2011-05-12 17:00:00,0.125,0.0,0.0,0.000000,0.000000,0.0,0.0,0.275,...,0.514286,0.363636,0.366667,0.739130,0.500000,0.0,1.0,1.0,Secure,0
1621204,ZSL0305,2011-05-13 09:00:00,0.125,0.0,0.0,0.000000,0.000000,0.0,0.0,0.275,...,0.514286,0.363636,0.400000,0.391304,0.666667,0.0,1.0,1.0,Secure,0
1621205,ZSL0305,2011-05-13 17:00:00,0.125,0.0,0.0,0.027778,0.022648,0.0,0.0,0.275,...,0.514286,0.363636,0.400000,0.739130,0.666667,0.0,1.0,1.0,Secure,0
1621206,ZSL0305,2011-05-16 09:00:00,0.125,0.0,0.0,0.000000,0.000000,0.0,0.0,0.275,...,0.514286,0.363636,0.500000,0.391304,0.000000,0.0,1.0,1.0,Secure,0
1621207,ZSL0305,2011-05-16 11:00:00,0.000,0.0,0.0,0.027778,0.021668,0.0,0.0,0.275,...,0.514286,0.363636,0.500000,0.478261,0.000000,0.0,1.0,1.0,Secure,0
1621208,ZSL0305,2011-05-16 17:00:00,0.125,0.0,0.0,0.000000,0.000000,0.0,0.0,0.275,...,0.514286,0.363636,0.500000,0.739130,0.000000,0.0,1.0,1.0,Secure,0